import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import QueryButton from "@/components/QueryButton";
import SearchBar from "@/components/SearchBar";
import TrendingTopics from "@/components/TrendingTopics";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-main-cream`}>
        <TopBar />

        <main className="flex flex-col items-center space-y-10 my-20">
          <TrendingTopics />
          <SearchBar />
        </main>
        <div className="container m-auto">{children}</div>
      </body>
    </html>
  );
}
