import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import QueryButton from "@/components/QueryButton";
import SearchBar from "@/components/SearchBar";
import TrendingTopics from "@/components/TrendingTopics";
import SearchSuggestions from "@/components/SearchSuggestions";
import QueryBuilder from "@/components/QueryBuilder";
import QueryClientProvider from "@/lib/queryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-main-cream`}>
        <QueryClientProvider>
          <TopBar />
          <main className="flex flex-col items-center space-y-20 my-20 container m-auto">
            <TrendingTopics />
            <SearchBar />
            <SearchSuggestions />
            <QueryBuilder />
            <div>{children}</div>
          </main>
          <div className="container m-auto">{children}</div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
