services:
  db:
    image: mysql:latest
    restart: always
    env_file: ".env"
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - db-data:/var/lib/mysql
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

volumes:
  db-data:
